title: Open Imaging Tools
description: A community directory of open-source software across neuroimaging modalities.
baseurl: ""
url: "https://openimagingtools.com"

plugins:
  - jekyll-sitemap

exclude:
  - scripts/
  - Gemfile
  - Gemfile.lock
