title: Open Imaging Tools
description: A community directory of open-source neuroimaging software across all modalities.
baseurl: ""
url: "https://openimagingtools.com"

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
